### ISSUE TITLE
I wonder what if take the glove as the word embedding

### ISSUE THREAD

**Issue by leekum2018** [mstrise/dep2label#1]
Excuse me.  I have already read your paper and I have benefited a lot.  But I wonder what if take the glove as the word embedding , how does the accuracy changes ? Iif you have done this experiment? And do you mind telling me the result?

**Comment by mstrise** [comment]
In the initial stage of implementing our approach we actually used Glove but then in order to give a fair comparison with BistParser we used the same embeddings and setup as in their work. The embeddings indeed have improved the score. Although, as long as I remember the improvement wasn't significant.
